timeout: 1000s
steps:
- name: node
  entrypoint: npm
  args: ["ci", "--prefix", "ReactJS"]
- name: node
  entrypoint: npm
  args: ["run", "bundle", "--prefix", "ReactJS"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "--promote"]